name: Terraform plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.rego"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Setup OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.59.0/opa_linux_amd64_static
          chmod 755 ./opa
          sudo mv ./opa /usr/local/bin/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Show Plan
        run: terraform show -json tfplan.binary > tfplan.json

      - name: OPA Check
        run: |
          VIOLATIONS=$(opa eval --format raw --data policies/restrict-ec2-type-t2micro.rego --input tfplan.json "data.terraform.deny")
          if [ "$VIOLATIONS" != "[]" ]; then
            echo "Policy violations found:"
            echo "$VIOLATIONS"
            exit 1
          fi

      - name: Add Plan to PR
        run: |
          terraform show -no-color tfplan.binary > tfplan.txt
          echo "\`\`\`hcl" >> plan.txt
          cat tfplan.txt >> plan.txt
          echo "\`\`\`" >> plan.txt
          gh pr comment ${{ github.event.pull_request.number }} -F plan.txt
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
